#!/usr/bin/env python3
"""Extract the initialisation state a synth --relocatable image does NOT carry.

AFD-046 lowered the full falcon cascade for cortex-m4f by declaring two embedder
obligations to synth:

    --embedder-data-init    (#1041) jess populates memory 0's active data segments
    --embedder-global-init  (#1052) jess seeds the R9 globals table from the module's
                                    initialisers, before any export runs

Those flags emit BYTE-IDENTICAL code. They convert a refusal into an acknowledgement
and nothing more, so they are promises, not configuration. If jess does not keep them,
every load from the initialised region and every global.get reads whatever the target
memory happens to hold — the gale#278 0xFF class. This tool produces the data needed
to keep them, in a form an ARM embedder can link.

It does NOT verify itself. verify_init.py does that, by differential against wasmtime.
"""
import argparse, json, struct, sys, subprocess, re


def wat(path: str) -> str:
    return subprocess.run(["wasm-tools", "print", path], capture_output=True,
                          text=True, check=True).stdout


def parse_globals(text: str):
    """Global initialisers, in declaration order (the R9 table's layout)."""
    out = []
    for i, line in enumerate(l for l in text.splitlines() if re.match(r'\s*\(global ', l)):
        # The `$name` is OPTIONAL: `wasm-tools print` keeps a symbolic name when the
        # module carries one (`(global $g (;0;) ...)`) and omits it when stripped. The
        # cascade is stripped, so requiring the stripped form parsed every real input
        # and rejected every hand-written one — a named const global was refused with
        # "a non-const initialiser cannot be seeded", which is the wrong reason.
        m = re.search(r'\(global\s+(?:\$[^\s()]+\s+)?\(;(\d+);\)\s+(\(mut\s+)?(\w+)\)?\s+(\w+)\.const\s+(-?\d+)', line)
        if not m:
            raise SystemExit(f"unparsed global (line {i}): {line.strip()}\n"
                             "  A non-const initialiser cannot be seeded from a static table;\n"
                             "  synth #1052 refuses those for the same reason. Failing loudly.")
        idx, mut, ty, cty, val = m.group(1), bool(m.group(2)), m.group(3), m.group(4), int(m.group(5))
        out.append({"index": int(idx), "type": ty, "mutable": mut, "value": val & 0xFFFFFFFF})
    return out


def parse_data(path: str, text: str):
    """Active data segments as (dest_offset, bytes).

    Read from the WAT rather than hand-rolling a binary parser: `wasm-tools print`
    already normalises the escapes, and a second parser is a second thing to get wrong.
    """
    segs, pending = [], None
    for line in text.splitlines():
        # Same optional-`$name` tolerance as parse_globals, for the same reason.
        m = re.match(r'\s*\(data\s+(?:\$[^\s()]+\s+)?\(;(\d+);\)\s+\(i32\.const (\d+)\)\s*(.*)', line)
        if m:
            if pending: segs.append(pending)
            pending = {"index": int(m.group(1)), "offset": int(m.group(2)), "raw": m.group(3)}
        elif pending is not None:
            pending["raw"] += line
    if pending: segs.append(pending)

    for s in segs:
        body = s.pop("raw")
        q = re.search(r'"((?:[^"\\]|\\.)*)"', body, re.S)
        s["bytes"] = decode_wat_string(q.group(1)) if q else b""
    return segs


def decode_wat_string(s: str) -> bytes:
    out, i = bytearray(), 0
    while i < len(s):
        if s[i] == "\\" and i + 2 < len(s) + 1:
            nxt = s[i+1]
            if nxt in "0123456789abcdefABCDEF" and i + 2 < len(s):
                out.append(int(s[i+1:i+3], 16)); i += 3; continue
            mapping = {"t": 9, "n": 10, "r": 13, '"': 34, "'": 39, "\\": 92}
            if nxt in mapping:
                out.append(mapping[nxt]); i += 2; continue
        out.append(ord(s[i])); i += 1
    return bytes(out)


def emit_c(segs, globs, module, out_c):
    total = sum(len(s["bytes"]) for s in segs)
    lines = [
        "/* GENERATED by tools/embedder-init/extract_init.py — do not edit.",
        f" * source module: {module}",
        " *",
        " * The initialisation state a synth --relocatable object does NOT carry.",
        " * Apply BOTH tables before calling any export, or every load from the",
        " * initialised region and every global.get reads uninitialised target memory.",
        " *",
        " * FREESTANDING BY CONSTRUCTION: no <stdint.h>, no <stddef.h>. This is compiled",
        " * by a bare-metal cross toolchain that may ship no libc headers at all (homebrew's",
        " * arm-none-eabi-gcc does not), and an embedder-init table that cannot be compiled",
        " * for the target it initialises is not a linkable form.",
        " */",
        "typedef unsigned char jess_u8;",
        "typedef unsigned int  jess_u32;    /* 32-bit on every ARM EABI target */",
        "typedef unsigned long jess_usize;",
        "",
        f"/* {len(segs)} active data segment(s), {total} bytes total */",
        "const jess_u8 jess_wasm_data_blob[] = {",
    ]
    blob = b"".join(s["bytes"] for s in segs)
    for i in range(0, len(blob), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i+16]) + ",")
    lines += ["};", "",
              "typedef struct { jess_u32 dst; jess_u32 off; jess_u32 len; } jess_seg_t;",
              f"const jess_seg_t jess_wasm_data_segs[{len(segs)}] = {{"]
    off = 0
    for s in segs:
        lines.append(f"    {{ {s['offset']}u, {off}u, {len(s['bytes'])}u }},  /* seg {s['index']} */")
        off += len(s["bytes"])
    lines += ["};", f"const jess_usize jess_wasm_data_seg_count = {len(segs)};", "",
              f"/* {len(globs)} global initialiser(s) — seed the R9 table in this order */",
              f"const jess_u32 jess_wasm_global_init[{len(globs)}] = {{"]
    for g in globs:
        lines.append(f"    0x{g['value']:08x}u,  /* global {g['index']} {'(mut) ' if g['mutable'] else ''}{g['type']} */")
    lines += ["};", f"const jess_usize jess_wasm_global_count = {len(globs)};", ""]
    open(out_c, "w").write("\n".join(lines) + "\n")
    return total


SELF_TEST_CASES = [
    # (label, WAT line as `wasm-tools print` emits it, expected parse or None to refuse)
    ("anonymous global", "  (global (;0;) (mut i32) i32.const 1515847680)", 0x5A5A0000),
    # THE REGRESSION: `wasm-tools print` keeps a symbolic name when the module carries
    # one. The cascade is name-stripped, so the old pattern matched every real input and
    # refused every hand-written one — reporting a plain const global as "a non-const
    # initialiser", which is a wrong diagnosis, not just a miss.
    ("named global", "  (global $g (;0;) (mut i32) i32.const 1515847680)", 0x5A5A0000),
    ("immutable named", "  (global $c (;1;) i32 i32.const 7)", 7),
    # Negative control: a genuinely non-const initialiser MUST still be refused. Without
    # this row, a regex loosened until everything matches would pass the two rows above.
    ("global.get init (must refuse)", "  (global (;0;) (mut i32) global.get 0)", None),
]


def self_test() -> int:
    ok = True
    for label, line, want in SELF_TEST_CASES:
        try:
            got = parse_globals(line)
            got = got[0]["value"] if got else "no-match"
        except SystemExit:
            got = None
        hit = (got == want)
        ok &= hit
        shown = got if got is None else (got if isinstance(got, str) else hex(got))
        wanted = want if want is None else (want if isinstance(want, str) else hex(want))
        print(f"  [{'ok ' if hit else 'FAIL'}] {label:<32} got={shown} want={wanted}")
    print("SELF-TEST:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("module", nargs="?")
    ap.add_argument("--out-c")
    ap.add_argument("--out-manifest")
    ap.add_argument("--self-test", action="store_true",
                    help="parser regression cases incl. a must-refuse negative control")
    a = ap.parse_args()
    if a.self_test:
        raise SystemExit(self_test())
    if not (a.module and a.out_c and a.out_manifest):
        ap.error("module, --out-c and --out-manifest are required")

    text = wat(a.module)
    segs, globs = parse_data(a.module, text), parse_globals(text)
    if not segs and not globs:
        raise SystemExit("no data segments and no globals — nothing to extract; refusing to "
                         "emit an empty init that would silently satisfy the obligation")
    total = emit_c(segs, globs, a.module, a.out_c)
    json.dump({"module": a.module,
               "segments": [{"index": s["index"], "offset": s["offset"], "len": len(s["bytes"])} for s in segs],
               "globals": globs, "data_bytes": total},
              open(a.out_manifest, "w"), indent=2)
    print(f"  {len(segs)} data segment(s), {total} bytes")
    print(f"  {len(globs)} global initialiser(s)")
    print(f"  -> {a.out_c}\n  -> {a.out_manifest}")


if __name__ == "__main__":
    sys.exit(main())
