#!/usr/bin/env python3
"""Extract the initialisation state a synth --relocatable image does NOT carry.

AFD-046 lowered the full falcon cascade for cortex-m4f by declaring two embedder
obligations to synth:

    --embedder-data-init    (#1041) jess populates memory 0's active data segments
    --embedder-global-init  (#1052) jess seeds the R9 globals table from the module's
                                    initialisers, before any export runs

Those flags emit BYTE-IDENTICAL code. They convert a refusal into an acknowledgement
and nothing more, so they are promises, not configuration. If jess does not keep them,
every load from the initialised region and every global.get reads whatever the target
memory happens to hold — the gale#278 0xFF class. This tool produces the data needed
to keep them, in a form an ARM embedder can link.

It does NOT verify itself. verify_init.py does that, by differential against wasmtime.
"""
import argparse, json, struct, sys, subprocess, re


def wat(path: str) -> str:
    return subprocess.run(["wasm-tools", "print", path], capture_output=True,
                          text=True, check=True).stdout


def parse_globals(text: str):
    """Global initialisers, in declaration order (the R9 table's layout)."""
    out = []
    for i, line in enumerate(l for l in text.splitlines() if re.match(r'\s*\(global ', l)):
        m = re.search(r'\(global \(;(\d+);\)\s+(\(mut\s+)?(\w+)\)?\s+(\w+)\.const\s+(-?\d+)', line)
        if not m:
            raise SystemExit(f"unparsed global (line {i}): {line.strip()}\n"
                             "  A non-const initialiser cannot be seeded from a static table;\n"
                             "  synth #1052 refuses those for the same reason. Failing loudly.")
        idx, mut, ty, cty, val = m.group(1), bool(m.group(2)), m.group(3), m.group(4), int(m.group(5))
        out.append({"index": int(idx), "type": ty, "mutable": mut, "value": val & 0xFFFFFFFF})
    return out


def parse_data(path: str, text: str):
    """Active data segments as (dest_offset, bytes).

    Read from the WAT rather than hand-rolling a binary parser: `wasm-tools print`
    already normalises the escapes, and a second parser is a second thing to get wrong.
    """
    segs, pending = [], None
    for line in text.splitlines():
        m = re.match(r'\s*\(data \(;(\d+);\) \(i32\.const (\d+)\)\s*(.*)', line)
        if m:
            if pending: segs.append(pending)
            pending = {"index": int(m.group(1)), "offset": int(m.group(2)), "raw": m.group(3)}
        elif pending is not None:
            pending["raw"] += line
    if pending: segs.append(pending)

    for s in segs:
        body = s.pop("raw")
        q = re.search(r'"((?:[^"\\]|\\.)*)"', body, re.S)
        s["bytes"] = decode_wat_string(q.group(1)) if q else b""
    return segs


def decode_wat_string(s: str) -> bytes:
    out, i = bytearray(), 0
    while i < len(s):
        if s[i] == "\\" and i + 2 < len(s) + 1:
            nxt = s[i+1]
            if nxt in "0123456789abcdefABCDEF" and i + 2 < len(s):
                out.append(int(s[i+1:i+3], 16)); i += 3; continue
            mapping = {"t": 9, "n": 10, "r": 13, '"': 34, "'": 39, "\\": 92}
            if nxt in mapping:
                out.append(mapping[nxt]); i += 2; continue
        out.append(ord(s[i])); i += 1
    return bytes(out)


def emit_c(segs, globs, module, out_c):
    total = sum(len(s["bytes"]) for s in segs)
    lines = [
        "/* GENERATED by tools/embedder-init/extract_init.py — do not edit.",
        f" * source module: {module}",
        " *",
        " * The initialisation state a synth --relocatable object does NOT carry.",
        " * Apply BOTH tables before calling any export, or every load from the",
        " * initialised region and every global.get reads uninitialised target memory.",
        " */",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"/* {len(segs)} active data segment(s), {total} bytes total */",
        "const uint8_t jess_wasm_data_blob[] = {",
    ]
    blob = b"".join(s["bytes"] for s in segs)
    for i in range(0, len(blob), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i+16]) + ",")
    lines += ["};", "",
              "typedef struct { uint32_t dst; uint32_t off; uint32_t len; } jess_seg_t;",
              f"const jess_seg_t jess_wasm_data_segs[{len(segs)}] = {{"]
    off = 0
    for s in segs:
        lines.append(f"    {{ {s['offset']}u, {off}u, {len(s['bytes'])}u }},  /* seg {s['index']} */")
        off += len(s["bytes"])
    lines += ["};", f"const size_t jess_wasm_data_seg_count = {len(segs)};", "",
              f"/* {len(globs)} global initialiser(s) — seed the R9 table in this order */",
              f"const uint32_t jess_wasm_global_init[{len(globs)}] = {{"]
    for g in globs:
        lines.append(f"    0x{g['value']:08x}u,  /* global {g['index']} {'(mut) ' if g['mutable'] else ''}{g['type']} */")
    lines += ["};", f"const size_t jess_wasm_global_count = {len(globs)};", ""]
    open(out_c, "w").write("\n".join(lines) + "\n")
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("module")
    ap.add_argument("--out-c", required=True)
    ap.add_argument("--out-manifest", required=True)
    a = ap.parse_args()

    text = wat(a.module)
    segs, globs = parse_data(a.module, text), parse_globals(text)
    if not segs and not globs:
        raise SystemExit("no data segments and no globals — nothing to extract; refusing to "
                         "emit an empty init that would silently satisfy the obligation")
    total = emit_c(segs, globs, a.module, a.out_c)
    json.dump({"module": a.module,
               "segments": [{"index": s["index"], "offset": s["offset"], "len": len(s["bytes"])} for s in segs],
               "globals": globs, "data_bytes": total},
              open(a.out_manifest, "w"), indent=2)
    print(f"  {len(segs)} data segment(s), {total} bytes")
    print(f"  {len(globs)} global initialiser(s)")
    print(f"  -> {a.out_c}\n  -> {a.out_manifest}")


if __name__ == "__main__":
    sys.exit(main())
